//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBO.diagnosticoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", ConfigurationName="diagnosticoWS.DiagnosticoWS")]
    public interface DiagnosticoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softcitws.soft.pucp.edu.pe/DiagnosticoWS/obtenerPorIdDiagnosticoRequest", ReplyAction="http://softcitws.soft.pucp.edu.pe/DiagnosticoWS/obtenerPorIdDiagnosticoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBO.diagnosticoWS.obtenerPorIdDiagnosticoResponse obtenerPorIdDiagnostico(SoftBO.diagnosticoWS.obtenerPorIdDiagnosticoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softcitws.soft.pucp.edu.pe/DiagnosticoWS/obtenerPorIdDiagnosticoRequest", ReplyAction="http://softcitws.soft.pucp.edu.pe/DiagnosticoWS/obtenerPorIdDiagnosticoResponse")]
        System.Threading.Tasks.Task<SoftBO.diagnosticoWS.obtenerPorIdDiagnosticoResponse> obtenerPorIdDiagnosticoAsync(SoftBO.diagnosticoWS.obtenerPorIdDiagnosticoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softcitws.soft.pucp.edu.pe/DiagnosticoWS/insertarDiagnosticoRequest", ReplyAction="http://softcitws.soft.pucp.edu.pe/DiagnosticoWS/insertarDiagnosticoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBO.diagnosticoWS.insertarDiagnosticoResponse insertarDiagnostico(SoftBO.diagnosticoWS.insertarDiagnosticoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softcitws.soft.pucp.edu.pe/DiagnosticoWS/insertarDiagnosticoRequest", ReplyAction="http://softcitws.soft.pucp.edu.pe/DiagnosticoWS/insertarDiagnosticoResponse")]
        System.Threading.Tasks.Task<SoftBO.diagnosticoWS.insertarDiagnosticoResponse> insertarDiagnosticoAsync(SoftBO.diagnosticoWS.insertarDiagnosticoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softcitws.soft.pucp.edu.pe/DiagnosticoWS/listarTodosDiagnosticoRequest", ReplyAction="http://softcitws.soft.pucp.edu.pe/DiagnosticoWS/listarTodosDiagnosticoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBO.diagnosticoWS.listarTodosDiagnosticoResponse listarTodosDiagnostico(SoftBO.diagnosticoWS.listarTodosDiagnosticoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softcitws.soft.pucp.edu.pe/DiagnosticoWS/listarTodosDiagnosticoRequest", ReplyAction="http://softcitws.soft.pucp.edu.pe/DiagnosticoWS/listarTodosDiagnosticoResponse")]
        System.Threading.Tasks.Task<SoftBO.diagnosticoWS.listarTodosDiagnosticoResponse> listarTodosDiagnosticoAsync(SoftBO.diagnosticoWS.listarTodosDiagnosticoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/")]
    public partial class diagnosticoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string capituloField;
        
        private string descripcionField;
        
        private string grupoField;
        
        private int idDiagnosticoField;
        
        private bool idDiagnosticoFieldSpecified;
        
        private int nivelField;
        
        private bool nivelFieldSpecified;
        
        private string nombreDiagnosticoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string capitulo {
            get {
                return this.capituloField;
            }
            set {
                this.capituloField = value;
                this.RaisePropertyChanged("capitulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string grupo {
            get {
                return this.grupoField;
            }
            set {
                this.grupoField = value;
                this.RaisePropertyChanged("grupo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idDiagnostico {
            get {
                return this.idDiagnosticoField;
            }
            set {
                this.idDiagnosticoField = value;
                this.RaisePropertyChanged("idDiagnostico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idDiagnosticoSpecified {
            get {
                return this.idDiagnosticoFieldSpecified;
            }
            set {
                this.idDiagnosticoFieldSpecified = value;
                this.RaisePropertyChanged("idDiagnosticoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
                this.RaisePropertyChanged("nivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nivelSpecified {
            get {
                return this.nivelFieldSpecified;
            }
            set {
                this.nivelFieldSpecified = value;
                this.RaisePropertyChanged("nivelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombreDiagnostico {
            get {
                return this.nombreDiagnosticoField;
            }
            set {
                this.nombreDiagnosticoField = value;
                this.RaisePropertyChanged("nombreDiagnostico");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdDiagnostico", WrapperNamespace="http://softcitws.soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdDiagnosticoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int diagnosticoId;
        
        public obtenerPorIdDiagnosticoRequest() {
        }
        
        public obtenerPorIdDiagnosticoRequest(int diagnosticoId) {
            this.diagnosticoId = diagnosticoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdDiagnosticoResponse", WrapperNamespace="http://softcitws.soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdDiagnosticoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBO.diagnosticoWS.diagnosticoDTO @return;
        
        public obtenerPorIdDiagnosticoResponse() {
        }
        
        public obtenerPorIdDiagnosticoResponse(SoftBO.diagnosticoWS.diagnosticoDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarDiagnostico", WrapperNamespace="http://softcitws.soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarDiagnosticoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBO.diagnosticoWS.diagnosticoDTO diagnostico;
        
        public insertarDiagnosticoRequest() {
        }
        
        public insertarDiagnosticoRequest(SoftBO.diagnosticoWS.diagnosticoDTO diagnostico) {
            this.diagnostico = diagnostico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarDiagnosticoResponse", WrapperNamespace="http://softcitws.soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarDiagnosticoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarDiagnosticoResponse() {
        }
        
        public insertarDiagnosticoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosDiagnostico", WrapperNamespace="http://softcitws.soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosDiagnosticoRequest {
        
        public listarTodosDiagnosticoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosDiagnosticoResponse", WrapperNamespace="http://softcitws.soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosDiagnosticoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBO.diagnosticoWS.diagnosticoDTO[] @return;
        
        public listarTodosDiagnosticoResponse() {
        }
        
        public listarTodosDiagnosticoResponse(SoftBO.diagnosticoWS.diagnosticoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DiagnosticoWSChannel : SoftBO.diagnosticoWS.DiagnosticoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiagnosticoWSClient : System.ServiceModel.ClientBase<SoftBO.diagnosticoWS.DiagnosticoWS>, SoftBO.diagnosticoWS.DiagnosticoWS {
        
        public DiagnosticoWSClient() {
        }
        
        public DiagnosticoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiagnosticoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiagnosticoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiagnosticoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBO.diagnosticoWS.obtenerPorIdDiagnosticoResponse SoftBO.diagnosticoWS.DiagnosticoWS.obtenerPorIdDiagnostico(SoftBO.diagnosticoWS.obtenerPorIdDiagnosticoRequest request) {
            return base.Channel.obtenerPorIdDiagnostico(request);
        }
        
        public SoftBO.diagnosticoWS.diagnosticoDTO obtenerPorIdDiagnostico(int diagnosticoId) {
            SoftBO.diagnosticoWS.obtenerPorIdDiagnosticoRequest inValue = new SoftBO.diagnosticoWS.obtenerPorIdDiagnosticoRequest();
            inValue.diagnosticoId = diagnosticoId;
            SoftBO.diagnosticoWS.obtenerPorIdDiagnosticoResponse retVal = ((SoftBO.diagnosticoWS.DiagnosticoWS)(this)).obtenerPorIdDiagnostico(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBO.diagnosticoWS.obtenerPorIdDiagnosticoResponse> SoftBO.diagnosticoWS.DiagnosticoWS.obtenerPorIdDiagnosticoAsync(SoftBO.diagnosticoWS.obtenerPorIdDiagnosticoRequest request) {
            return base.Channel.obtenerPorIdDiagnosticoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBO.diagnosticoWS.obtenerPorIdDiagnosticoResponse> obtenerPorIdDiagnosticoAsync(int diagnosticoId) {
            SoftBO.diagnosticoWS.obtenerPorIdDiagnosticoRequest inValue = new SoftBO.diagnosticoWS.obtenerPorIdDiagnosticoRequest();
            inValue.diagnosticoId = diagnosticoId;
            return ((SoftBO.diagnosticoWS.DiagnosticoWS)(this)).obtenerPorIdDiagnosticoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBO.diagnosticoWS.insertarDiagnosticoResponse SoftBO.diagnosticoWS.DiagnosticoWS.insertarDiagnostico(SoftBO.diagnosticoWS.insertarDiagnosticoRequest request) {
            return base.Channel.insertarDiagnostico(request);
        }
        
        public int insertarDiagnostico(SoftBO.diagnosticoWS.diagnosticoDTO diagnostico) {
            SoftBO.diagnosticoWS.insertarDiagnosticoRequest inValue = new SoftBO.diagnosticoWS.insertarDiagnosticoRequest();
            inValue.diagnostico = diagnostico;
            SoftBO.diagnosticoWS.insertarDiagnosticoResponse retVal = ((SoftBO.diagnosticoWS.DiagnosticoWS)(this)).insertarDiagnostico(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBO.diagnosticoWS.insertarDiagnosticoResponse> SoftBO.diagnosticoWS.DiagnosticoWS.insertarDiagnosticoAsync(SoftBO.diagnosticoWS.insertarDiagnosticoRequest request) {
            return base.Channel.insertarDiagnosticoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBO.diagnosticoWS.insertarDiagnosticoResponse> insertarDiagnosticoAsync(SoftBO.diagnosticoWS.diagnosticoDTO diagnostico) {
            SoftBO.diagnosticoWS.insertarDiagnosticoRequest inValue = new SoftBO.diagnosticoWS.insertarDiagnosticoRequest();
            inValue.diagnostico = diagnostico;
            return ((SoftBO.diagnosticoWS.DiagnosticoWS)(this)).insertarDiagnosticoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBO.diagnosticoWS.listarTodosDiagnosticoResponse SoftBO.diagnosticoWS.DiagnosticoWS.listarTodosDiagnostico(SoftBO.diagnosticoWS.listarTodosDiagnosticoRequest request) {
            return base.Channel.listarTodosDiagnostico(request);
        }
        
        public SoftBO.diagnosticoWS.diagnosticoDTO[] listarTodosDiagnostico() {
            SoftBO.diagnosticoWS.listarTodosDiagnosticoRequest inValue = new SoftBO.diagnosticoWS.listarTodosDiagnosticoRequest();
            SoftBO.diagnosticoWS.listarTodosDiagnosticoResponse retVal = ((SoftBO.diagnosticoWS.DiagnosticoWS)(this)).listarTodosDiagnostico(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBO.diagnosticoWS.listarTodosDiagnosticoResponse> SoftBO.diagnosticoWS.DiagnosticoWS.listarTodosDiagnosticoAsync(SoftBO.diagnosticoWS.listarTodosDiagnosticoRequest request) {
            return base.Channel.listarTodosDiagnosticoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBO.diagnosticoWS.listarTodosDiagnosticoResponse> listarTodosDiagnosticoAsync() {
            SoftBO.diagnosticoWS.listarTodosDiagnosticoRequest inValue = new SoftBO.diagnosticoWS.listarTodosDiagnosticoRequest();
            return ((SoftBO.diagnosticoWS.DiagnosticoWS)(this)).listarTodosDiagnosticoAsync(inValue);
        }
    }
}
