//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBO.loginWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", ConfigurationName="loginWS.LoginWS")]
    public interface LoginWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softcitws.soft.pucp.edu.pe/LoginWS/iniciarSesionRequest", ReplyAction="http://softcitws.soft.pucp.edu.pe/LoginWS/iniciarSesionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBO.loginWS.iniciarSesionResponse iniciarSesion(SoftBO.loginWS.iniciarSesionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softcitws.soft.pucp.edu.pe/LoginWS/iniciarSesionRequest", ReplyAction="http://softcitws.soft.pucp.edu.pe/LoginWS/iniciarSesionResponse")]
        System.Threading.Tasks.Task<SoftBO.loginWS.iniciarSesionResponse> iniciarSesionAsync(SoftBO.loginWS.iniciarSesionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softcitws.soft.pucp.edu.pe/LoginWS/cerrarSesionRequest", ReplyAction="http://softcitws.soft.pucp.edu.pe/LoginWS/cerrarSesionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBO.loginWS.cerrarSesionResponse cerrarSesion(SoftBO.loginWS.cerrarSesionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softcitws.soft.pucp.edu.pe/LoginWS/cerrarSesionRequest", ReplyAction="http://softcitws.soft.pucp.edu.pe/LoginWS/cerrarSesionResponse")]
        System.Threading.Tasks.Task<SoftBO.loginWS.cerrarSesionResponse> cerrarSesionAsync(SoftBO.loginWS.cerrarSesionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string codMedicoField;
        
        private string contrasenhaField;
        
        private string correoElectronicoField;
        
        private estadoGeneral estadoGeneralField;
        
        private bool estadoGeneralFieldSpecified;
        
        private estadoLogico estadoLogicoField;
        
        private bool estadoLogicoFieldSpecified;
        
        private localDate fechaNacimientoField;
        
        private genero generoField;
        
        private bool generoFieldSpecified;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nombresField;
        
        private string numCelularField;
        
        private string numDocumentoField;
        
        private System.Nullable<int>[] rolesField;
        
        private tipoDocumento tipoDocumentoField;
        
        private bool tipoDocumentoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codMedico {
            get {
                return this.codMedicoField;
            }
            set {
                this.codMedicoField = value;
                this.RaisePropertyChanged("codMedico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string contrasenha {
            get {
                return this.contrasenhaField;
            }
            set {
                this.contrasenhaField = value;
                this.RaisePropertyChanged("contrasenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
                this.RaisePropertyChanged("correoElectronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public estadoGeneral estadoGeneral {
            get {
                return this.estadoGeneralField;
            }
            set {
                this.estadoGeneralField = value;
                this.RaisePropertyChanged("estadoGeneral");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoGeneralSpecified {
            get {
                return this.estadoGeneralFieldSpecified;
            }
            set {
                this.estadoGeneralFieldSpecified = value;
                this.RaisePropertyChanged("estadoGeneralSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public estadoLogico estadoLogico {
            get {
                return this.estadoLogicoField;
            }
            set {
                this.estadoLogicoField = value;
                this.RaisePropertyChanged("estadoLogico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoLogicoSpecified {
            get {
                return this.estadoLogicoFieldSpecified;
            }
            set {
                this.estadoLogicoFieldSpecified = value;
                this.RaisePropertyChanged("estadoLogicoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public localDate fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public genero genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generoSpecified {
            get {
                return this.generoFieldSpecified;
            }
            set {
                this.generoFieldSpecified = value;
                this.RaisePropertyChanged("generoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string numCelular {
            get {
                return this.numCelularField;
            }
            set {
                this.numCelularField = value;
                this.RaisePropertyChanged("numCelular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string numDocumento {
            get {
                return this.numDocumentoField;
            }
            set {
                this.numDocumentoField = value;
                this.RaisePropertyChanged("numDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("roles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public System.Nullable<int>[] roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
                this.RaisePropertyChanged("roles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public tipoDocumento tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDocumentoSpecified {
            get {
                return this.tipoDocumentoFieldSpecified;
            }
            set {
                this.tipoDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("tipoDocumentoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/")]
    public enum estadoGeneral {
        
        /// <remarks/>
        INACTIVO,
        
        /// <remarks/>
        ACTIVO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/")]
    public enum estadoLogico {
        
        /// <remarks/>
        AUSENTE,
        
        /// <remarks/>
        DISPONIBLE,
        
        /// <remarks/>
        DE_VACACIONES,
        
        /// <remarks/>
        DE_BAJA,
        
        /// <remarks/>
        EN_CAPACITACION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/")]
    public partial class localDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/")]
    public enum genero {
        
        /// <remarks/>
        FEMENINO,
        
        /// <remarks/>
        MASCULINO,
        
        /// <remarks/>
        OTRO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/")]
    public enum tipoDocumento {
        
        /// <remarks/>
        DNI,
        
        /// <remarks/>
        CE,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iniciarSesion", WrapperNamespace="http://softcitws.soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class iniciarSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenha;
        
        public iniciarSesionRequest() {
        }
        
        public iniciarSesionRequest(string numeroDoc, string tipoDoc, string contrasenha) {
            this.numeroDoc = numeroDoc;
            this.tipoDoc = tipoDoc;
            this.contrasenha = contrasenha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iniciarSesionResponse", WrapperNamespace="http://softcitws.soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class iniciarSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBO.loginWS.usuarioDTO @return;
        
        public iniciarSesionResponse() {
        }
        
        public iniciarSesionResponse(SoftBO.loginWS.usuarioDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cerrarSesion", WrapperNamespace="http://softcitws.soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class cerrarSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBO.loginWS.usuarioDTO usuarioDTO;
        
        public cerrarSesionRequest() {
        }
        
        public cerrarSesionRequest(SoftBO.loginWS.usuarioDTO usuarioDTO) {
            this.usuarioDTO = usuarioDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cerrarSesionResponse", WrapperNamespace="http://softcitws.soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class cerrarSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public cerrarSesionResponse() {
        }
        
        public cerrarSesionResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginWSChannel : SoftBO.loginWS.LoginWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginWSClient : System.ServiceModel.ClientBase<SoftBO.loginWS.LoginWS>, SoftBO.loginWS.LoginWS {
        
        public LoginWSClient() {
        }
        
        public LoginWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBO.loginWS.iniciarSesionResponse SoftBO.loginWS.LoginWS.iniciarSesion(SoftBO.loginWS.iniciarSesionRequest request) {
            return base.Channel.iniciarSesion(request);
        }
        
        public SoftBO.loginWS.usuarioDTO iniciarSesion(string numeroDoc, string tipoDoc, string contrasenha) {
            SoftBO.loginWS.iniciarSesionRequest inValue = new SoftBO.loginWS.iniciarSesionRequest();
            inValue.numeroDoc = numeroDoc;
            inValue.tipoDoc = tipoDoc;
            inValue.contrasenha = contrasenha;
            SoftBO.loginWS.iniciarSesionResponse retVal = ((SoftBO.loginWS.LoginWS)(this)).iniciarSesion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBO.loginWS.iniciarSesionResponse> SoftBO.loginWS.LoginWS.iniciarSesionAsync(SoftBO.loginWS.iniciarSesionRequest request) {
            return base.Channel.iniciarSesionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBO.loginWS.iniciarSesionResponse> iniciarSesionAsync(string numeroDoc, string tipoDoc, string contrasenha) {
            SoftBO.loginWS.iniciarSesionRequest inValue = new SoftBO.loginWS.iniciarSesionRequest();
            inValue.numeroDoc = numeroDoc;
            inValue.tipoDoc = tipoDoc;
            inValue.contrasenha = contrasenha;
            return ((SoftBO.loginWS.LoginWS)(this)).iniciarSesionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBO.loginWS.cerrarSesionResponse SoftBO.loginWS.LoginWS.cerrarSesion(SoftBO.loginWS.cerrarSesionRequest request) {
            return base.Channel.cerrarSesion(request);
        }
        
        public bool cerrarSesion(SoftBO.loginWS.usuarioDTO usuarioDTO) {
            SoftBO.loginWS.cerrarSesionRequest inValue = new SoftBO.loginWS.cerrarSesionRequest();
            inValue.usuarioDTO = usuarioDTO;
            SoftBO.loginWS.cerrarSesionResponse retVal = ((SoftBO.loginWS.LoginWS)(this)).cerrarSesion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBO.loginWS.cerrarSesionResponse> SoftBO.loginWS.LoginWS.cerrarSesionAsync(SoftBO.loginWS.cerrarSesionRequest request) {
            return base.Channel.cerrarSesionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBO.loginWS.cerrarSesionResponse> cerrarSesionAsync(SoftBO.loginWS.usuarioDTO usuarioDTO) {
            SoftBO.loginWS.cerrarSesionRequest inValue = new SoftBO.loginWS.cerrarSesionRequest();
            inValue.usuarioDTO = usuarioDTO;
            return ((SoftBO.loginWS.LoginWS)(this)).cerrarSesionAsync(inValue);
        }
    }
}
